version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    environment:
      APP_URL: 'http://0.0.0.0:3000'
      APP_SECRET: 'a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0'
      DATABASE_URL: 'postgresql://docmost:6ki4sgdiz1otzao2@10.0.6.20:54321/docmost?schema=public'
      REDIS_URL: 'redis://:6ki4sgdiz1otzao2@10.0.6.20:63791'
    ports:
      - "12200:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

volumes:
  docmost:
