version: '3'

services:
  docmost:
    image: docmost/docmost:latest
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'REPLACE_WITH_LONG_SECRET'
      DATABASE_URL: 'postgresql://hyt-erp-dba:287ahohpgowlpj0d@10.0.3.161:5432/docmost?schema=public'
      REDIS_URL: 'redis://:287ahohpgowlpj0d@10.0.3.161:6379'
    ports:
      - "12200:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

volumes:
  docmost:
